# Generated by Django 4.1.3 on 2022-11-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="education_end",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_start",
            field=models.IntegerField(),
        ),
    ]
