# Generated by Django 4.1.3 on 2022-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_education_education_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_tools",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="certification",
            name="certification_date",
            field=models.DateField(default=None),
        ),
    ]
