# Generated by Django 4.1.3 on 2022-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_project_project_tools_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="certification_link",
            field=models.CharField(default="", max_length=100),
        ),
    ]
