# Generated by Django 4.1.3 on 2022-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_certification_certification_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_link",
            new_name="project_link_youtube",
        ),
        migrations.AddField(
            model_name="project",
            name="project_link_linkedin",
            field=models.TextField(default="", max_length=500),
        ),
    ]
