# Generated by Django 4.1.3 on 2022-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_rename_project_link_project_project_link_youtube_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_link_github",
            field=models.TextField(default="", max_length=500),
        ),
    ]
