# Generated by Django 4.1.3 on 2022-11-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_project_project_link_github"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="education_course",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="education",
            name="education_description",
            field=models.CharField(default="", max_length=500),
        ),
    ]
