# Generated by Django 4.1.3 on 2022-11-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_education_education_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="education_description",
            field=models.TextField(default="", max_length=5000),
        ),
    ]
