# Generated by Django 4.1.3 on 2022-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_alter_education_education_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="education_gpa",
            field=models.CharField(max_length=10),
        ),
    ]
