# Generated by Django 4.1.3 on 2022-11-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_alter_education_education_gpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="certification_link",
            field=models.TextField(default=""),
        ),
    ]
