# Generated by Django 4.1.3 on 2022-11-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_alter_certification_certification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_uupload_to_youtube",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="", max_length=100
            ),
        ),
    ]
