# Generated by Django 4.1.3 on 2022-11-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_project_project_uupload_to_youtube"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_uupload_to_youtube",
            new_name="project_upload_to_youtube",
        ),
    ]
