# Generated by Django 4.1.3 on 2022-11-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_role_logo",
            field=models.ImageField(
                blank=True, default="", upload_to="static/assets/uploads"
            ),
        ),
    ]
